repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]
-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [
          '--line-length=120'
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: [
          '--max-line-length=120'
        ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [
            '--profile=black',
            '--section-default=THIRDPARTY',
            '-l=120'
        ]
      - id: mypy
        name: mypy
        entry: mypy
        verbose: true
        language: system
        types: [ python ]
        require_serial: true
        args: [
          '--ignore-missing-imports',
          '--disallow-untyped-defs',
          '--warn-redundant-casts'
        ]
